<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::insert('insert into journals values(?,?,?,?,?,?,?,?,?,?,?)', [NULL,'Notes on common macrobenthic reef invertebrates of Tubbataha Reefs Natural Park, Philippines','Roger G. Dolorosa, Jean Beth S. Jontila','2012-12-01','Macrobenthic reef invertebrates are important reef health indicators and fishery resources but are not very well documented in Tubbataha Reefs Natural Park. To provide notes on the species composition and the abundance and size of commonly encountered macrobenthic reef invertebrates, belt transects survey in intertidal, shallow, and deep subtidal reef habitats were conducted. In total, 18 species were recorded, six of which were echinoderms and 12 were mollusks, which include the rare giant clam Hippopus porcellanus. Only the giant clam Tridacna crocea and the top shell Trochus niloticus occurred in all seven permanent monitoring sites but the two species varied in densities across depths. There was also an outbreak of crown-of-thorns (COTs) sea stars in some sites. The large variation in the density of each species across sites and depths suggests niche differences, overharvesting, or their recovery from having been overly exploited. Separate monitoring areas for each commercially important species are suggested to determine how their populations respond to poaching and their implications on the park’s long term management.','NationalCapitalRegion','Aquaculture','http://res.cloudinary.com/dzhe5doam/image/upload/c_fit/ut2s43pgoenuereumao3.pdf','HAHAHAHAAHAH',NULL,NULL]);


        DB::insert('insert into journals values(?,?,?,?,?,?,?,?,?,?,?)', [NULL,'An ethnomycological survey of macrofungi utilized by Aeta communities in Central Luzon, Philippines','De Leon AM, Reyes RG, dela Cruz TEE','2012-01-02','Questionnaires and formatted interviews were used to determine mushrooms used as food and as materials for societal rituals and beliefs among six Aeta communities in three provinces of Central Luzon, Northern Philippines. Thirty-eight different fungi were utilized by the Aeta communities: 21 in Pampanga, 10 in Tarlac, and 19 in Zambales. Fourteen fungal species were collected and identified based on their morphological characters: Auricularia auricula, A. polytricha, Calvatia sp., Ganoderma lucidum, Lentinus tigrinus, L. sajor-caju, Mycena sp., Pleurotus sp., Schizophyllum commune, Termitomyces clypeatus, T. robustus, Termitomyces sp. 1, Termitomyces sp. 2, and Volvariella volvacea. Twelve of the identified macrofungi were consumed as food while Ganoderma lucidum and Mycena sp. were used as house decoration and medicine, respectively. The Aeta communities also performed rituals prior to the collection of these mushrooms, including tribal dancing, praying and kissing the ground. Their indigenous beliefs regarding mushrooms are also documented. This is the most extensive enthnomycological study on the Aeta communities in the Philippines.','NationalCapitalRegion','History Sociology','http://res.cloudinary.com/dzhe5doam/image/upload/c_fit/s72ulfoolkezmonplu8n.pdf','HAHAHAHAAHAH',NULL,NULL]);


        DB::insert('insert into journals values(?,?,?,?,?,?,?,?,?,?,?)', [NULL,"ANALYZING THE IMPACTS OF LAND COVER CHANGE TO THE HYDROLOGIC AND HYDRAULIC BEHAVIOURS OF THE PHILIPPINES' THIRD LARGEST RIVER BASIN",'J.R. Santillan, A.M. Amora, M. Makinano-Santillan, A.L. Gingo, J.T. Marqueso','2019-03-14','Changes in land cover can have negative impacts on the hydrological and hydraulic processes in river basins and watersheds such as increase in surface runoff and peak flows, and greater incidence, risk and vulnerability of flooding. In this study, the impacts of landcover changes to the hydrologic and hydraulic behaviours of the Agusan River Basin (ARB), the third largest river basin in the Philippines, was analysed using an integrated approach involving Remote Sensing (RS), Geographic Information System (GIS), and hydrologic and hydraulic models. Different land-cover classes in the ARB for the years 1995 and 2017 were mapped using Landsat 5 TM and Landsat 8 OLI images. Using a post-classification change detection approach, changes in land-cover were then determined. The impacts of these changes in land-cover to the to the basin discharge were then estimated using a calibrated hydrologic model based on the Hydrologic Engineering Center - Hydrologic Modeling System (HEC-HMS) under different extreme rainfall conditions. The impact of the changes in land-cover to flood depth and extent was also determined using a hydraulic model based on the HEC-RAS (River Analysis System). Land cover classification results revealed that the ARB is 67.7% forest in 1995 but have decreased to 62.8% in 2017. Agricultural areas in the basin were also found to have increased from 12.2% to 15.5% in the same period. Other notable land cover changes detected include the increase in built-up lands and range lands, and decrease in barren lands. HEC HMS and HEC RAS model simulation results showed that there was an increase in discharge, flood depth, and flood extents between 1995 and 2017, implying that that the detected changes in land cover have negative impacts to hydrologic and hydraulic behaviours of the ARB.','NationalCapitalRegion','Aquaculture','http://res.cloudinary.com/dzhe5doam/image/upload/c_fit/javcamh85oecpxzfmdcf.pdf','HAHAHAHAAHAH',NULL,NULL]);

        DB::insert('insert into journals values(?,?,?,?,?,?,?,?,?,?,?)', [NULL,"Gender, Reflexivity, and Positionality in Male Research in One's Own Community With Filipino Seafarers' Wives",'Roderick G. Galam','2015-09-01',"This article reflects on the epistemological, methodological, and ethical issues related to undertaking a cross-gender research (male researcher with female participants) in one's own community. It also examines issues of analysis and representation germane to taking a gendered perspective in this study of the lives and experiences of left-behind women. The article frames the discussion of these issues within four interrelated sites or levels of reflexivity: theoretical reflexivity, gender and fieldwork relations, positionality and the insider/outsider dynamic, and representation. The conclusion reflects on the ethical obligation a researcher conducting a study in one's own community bears and the consequences of this ethical burden on representation.",'NationalCapitalRegion','Epistemology Ethics','http://res.cloudinary.com/dzhe5doam/image/upload/c_fit/fnxr3yshm2xvl0mu2wvl.pdf','HAHAHAHAAHAH',NULL,NULL]);

        DB::insert('insert into journals values(?,?,?,?,?,?,?,?,?,?,?)', [NULL,'“Pig’s Nest” in an Even Bigger Pen: Pugad Baboy as a Case of Subversion and Renegotiation in Philippine Comedy','Maria Rhodora G. Ancheta','2000-12-01','This paper discusses Pol Medina, Jr.’s contemporary comic strip Pugad Baboy as a case of subversion and renegotiation undergone by Philippine comedy. This paper posits that Medina’s innovation by way of the “novelization” of the comic strip, as exemplified here by “Ang Hiwaga ng Dueñas” (“The Dueñas Mystery”) from Pugad Baboy 4, illustrates and inscribes what can be deemed as comic interpretations of the gaps, distortions, and juxtapositions within Philippine culture. The reading of this contemporary Philippine comic strip leads us to examine abnormality, incongruity, inversions, and hyperreality as manifestations of current Philippine comedy, one that may be socially corrective, or culturally liminal, which now moves towards a depiction of comic postmodernity.','NationalCapitalRegion','Humanities','http://res.cloudinary.com/dzhe5doam/image/upload/c_fit/ktrh2k7buqnxggmhucox.pdf','HAHAHAHAAHAH',NULL,NULL]);

        DB::insert('insert into journals values(?,?,?,?,?,?,?,?,?,?,?)', [NULL,"Rizal's Legacy for the 21st Century: Progressive Education, Social Entrepreneurship and Community Development in Dapitan",'Floro Quibuyen','2011-12-01',"Rizal's four years in Dapitan have not been fully explored for the light they can shed on contemporary issues in community development and education. In particular, the significance of the school he founded in Talisay has not merited scholarly commentary. Those fruitful four years in Dapitan have become Rizal's most unappreciated legacy, yet they are precisely what make Rizal singularly relevant to the 21st century. This essay explains why.",'RegionI','Social Science','http://res.cloudinary.com/dzhe5doam/image/upload/c_fit/u4tr4hfk3neflayatgr5.pdf','HAHAHAHAAHAH',NULL,NULL]);

        DB::insert('insert into journals values(?,?,?,?,?,?,?,?,?,?,?)', [NULL,'A (FORENSIC) STYLISTIC ANALYSIS OF ADVERBIALS OF ATTITUDE AND EMPHASIS IN SUPREME COURT DECISIONS IN PHILIPPINE ENGLISH','Hjalmar Punla Hernandez','2017-09-26','Contemporarily, stylistics today has developed into its multiplicity – one of which is forensic stylistics. Being a powerfully legal written discourse, Supreme Court decisions are a rich corpus in which linguistic vis-a-vis stylistic choices of Court justices could be examined. This study is a humble attempt at stylistically analyzing Supreme Court decisions in Philippine English (PhE) drafted by two Filipino justices. Specifically, it sought to investigate on the classes, placements, and environments of adverbials of attitude and emphasis employed by the two justices, and drew their implications to teaching and learning English for Legal Purposes (ELP). Using McMenamin (2012), Quirk, Greenbaum, Leech, and Svartvik (1985), and Dita’s (2011) frameworks, 54 randomly selected Supreme Court decisions as primary sources of legal language were analyzed. Results are the following. Firstly, the classes of adverbials of attitude in Supreme Court decisions in PhE used by the two judges were the evaluation to the subject of the clause, judgment to the whole clause, and evaluation to an action performed by the subject of the clause, while those adverbials of emphasis were adverbials of conviction and doubt. Secondly, both adverbials they used have placements that were frequently medial and less initial in sentences where they belonged. Thirdly, the two justices put their adverbials within two principal environments, i.e. within functor, and before/after the verb among others. In these regards, legal and stylistic explanations with respect to these recurrent linguistic features in the two justices’ Court decisions were revealed. Implications of the study to ELP are explained. Lastly, trajectories for future (forensic) stylistic analyses have been recommended.','RegionI','Forensic Science','http://res.cloudinary.com/dzhe5doam/image/upload/c_fit/uvgp3l93dslzpwg9oglg.pdf','HAHAHAHAAHAH',NULL,NULL]);

        DB::insert('insert into journals values(?,?,?,?,?,?,?,?,?,?,?)', [NULL,'FEEDING ECOLOGY OF TREE-CLIMBING MANGROVE SESARMID CRABS FROM LUZON, PHILIPPINES','JIMMY TEVAR MASAGCA','2019-05-01','Despite the large ecological study of tree-climbing mangrove sesarmid crabs in other countries, the Philippine representatives appear to have not been investigated extensively. This paper presents the feeding ecology as to dependence on mangrove trees of sesarmids in different mangrove areas of southern Luzon. This is biased on the nature of the crab habitats, arboreal climbing skills and burrowing behavior of the sesarmids: Selatium elongatum and Episesarma versicolor − exclusive mangrove tree climbers (EMTC); Sarmatium germaini − occasional mangrove tree climber (OMTC); and the non-mangrove tree-climbing (NMTC) sesarmids- Neosarmatium smithii, Perisesarma bidens and Perisesarma eumolpe.','RegionI','Ecology','https://res.cloudinary.com/dzhe5doam/image/upload/v1557419094/knp9nn4wcfofa0f5qmgu.pdf','HAHAHAHAAHAH',NULL,NULL]);

        DB::insert('insert into journals values(?,?,?,?,?,?,?,?,?,?,?)', [NULL,'Logical Reasoning Abilities of Junior High School Students in the Province of Cotabato, Philippines','Paul John B. Ongcoy','2016-10-25','Reasoning abilities of the learners and its development was well-discussed in the world of education. The higher the ability of the person to reason abstractly, the higher the probability that a person will effectively function in the society. Thus, it is the main goal of the K-12 Curriculum of the Department of Education to improve the reasoning abilities and formal reasoning among students in the country. The higher the reasoning ability of a person, the more productive he is. The ability of logical reasoning has an essential function in the academic performance of students and their construction of the concepts. This study aimed to determine the logical reasoning abilities of 150 randomly selected junior high school students. Specifically, this study aimed to determine the logical reasoning abilities namely combinatorial reasoning, controlling variables, correlation reasoning, probabilistic reasoning and proportional reasoning among the grade 10 junior high school students and determine whether there is a significant difference in students’ logical reasoning abilities according to their gender. The respondents answered the Test of Logical Thinking (TOLT). Thirty respondents were interviewed to verify their answers. The findings of the study led to the following conclusions: most students correctly answered problems in probabilistic reasoning and least number of students correctly answered problems in proportional reasoning and combinatorial reasoning and, male and female respondents have equal performances in problems pertaining to combinatorial reasoning, controlling variables, correlational reasoning and probabilistic reasoning but female respondents are better in proportional reasoning than the male respondents.','RegionII','Social Science','http://res.cloudinary.com/dzhe5doam/image/upload/c_fit/jr0gmodij2syhp4xgvh6.pdf','HAHAHAHAAHAH',NULL,NULL]);

        DB::insert('insert into journals values(?,?,?,?,?,?,?,?,?,?,?)', [NULL,'Political Dynasty in Public Governance: A Close Encounter with the Cebuanos','Eron Anthony Guarde, Rufina C. Rosaroso, Fredrich Rama, Rolan Batac, Gerome Lasala','2016-04-03','This is a qualitative study which described the existence of political dynasties in Cebu, Philippines. The prevailing issues on political equality and perennial rule of political families were also investigated unfolding the Cebuanos’ perceptions of political dynasty and its impact on Cebuano bureaucracy. The method of data analysis used in the study was narrative inquiry where storytelling among the selected key informants served as data collection technique. Purposive sampling was used in the selection of key informant politicians while random sampling for key informant voters was determined. The instruments used in data gathering were interviews and observations. The study revealed the true meaning of political dynasty, its advantages and drawbacks to its constituents. Varied rejoinders and call for democracy motivated the selected key informant politicians to continue serving the citizenry. This study recommends that an anti-individualistic voting preferences campaign be promoted by the government, education and youth sectors in transforming intelligent Filipino voters.','RegionII','Social Science','http://res.cloudinary.com/dzhe5doam/image/upload/c_fit/onlws08c9nrz40p4zxf2.pdf','HAHAHAHAAHAH',NULL,NULL]);

        DB::insert('insert into journals values(?,?,?,?,?,?,?,?,?,?,?)', [NULL,'Establishing a soil reference system for fertility assessment and monitoring at plot level in the highlands of Mindanao, Philippines','Guadalupe D. Calalang, Laurent Bock, Gilles Colinet','2014-01-01','The study was conducted in the crop production areas of Miarayon Village, along the volcanic footslope of Mt. Kalatungan, Talakag, Bukidnon, Philippines. The elevation range of the longitudinal toposequence is 1,900 to 1,300 m asl. Production areas in the intermediate part of the toposequence (Salsalan) are located at about 1,600 to 1,400 m asl and in the lower part (Mambuaw) at 1,400 to 1,300 m asl. A total of 24 plots (12 in each location) which were planted to potatoes, carrots and corn were investigated. Soils are “Andic” Cambisol in open and convex positions and “Andic” Umbrisol in concave positions and toeslopes. The soil pH values ranged from 5.0-5.9. TOC and TN content were medium to high (4.1-8.9% and 0.30-0.80% respectively) with C/N ratios from 8-15. Range values of available Ca, Mg, K and Na were 1.9-11.24, 0.16-2.14 and 0.20-1.13, 0.04-0.13 cmol+kg-1, respectively. Top soil horizon exchangeable Al in Mambuaw was higher than in Salsalan. The differences in TN, C/N ratio and available K levels between the two locations were very highly significant, TOC was highly significant and for soil pH and available Ca and sum of bases, their disparities were significant. Available Mg and Na did not differ between the two sites. Mean potato yield in Salsalan was 8.97 tha-1 more than in Mambuaw. Mean carrot yield in Salsalan was 2.39 tha-1 lesser than in Mambuaw. Mean corn yield in Salsalan was higher than in Mambuaw by 0.29 tha-1 only. Correlations between potato yields with TOC, TN, and available Ca were highly significant while soil pH and K were significant. There was no relationship detected between potato yields and Mg and Na. There was no association detected between carrot yields with topsoil nutrient levels. Correlations were noted in corn yields with available Ca, Mg and K.','RegionII','Agriculture','http://res.cloudinary.com/dzhe5doam/image/upload/c_fit/pbwlul1hlb0qhwa7w8k6.pdf','HAHAHAHAAHAH',NULL,NULL]);

        DB::insert('insert into journals values(?,?,?,?,?,?,?,?,?,?,?)', [NULL,'Economic Difficulty and Coping Strategies of Low Income Faculty Members as Related to their Teaching Performance','Ronaldo F. Frufonga','2015-09-29',"This study ascertained the relationship between difficulties and coping strategies as related to teaching performance of West Visayas State University-Janiuay Campus (WVSU-JC) faculty for the School Year 2014-2015. The survey-correlational method was used with teaching performance as dependent variables, experienced economic difficulties as the independent variable, and coping strategy as moderator variable. The participants in the study were the 52 faculty who were selected through purposive sampling. Data were gathered through a researcher-made questionnaire-checklist and Faculty Performance Evaluation System. The statistical tools used were frequency count, rank, mean, standard deviation, and Pearson's Product-Moment Coefficient of Correlation. All statistical computations were availed of through the Statistical Package for the Social Sciences (SPSS) software. Results revealed that the top economic difficulty experienced by faculty was limited cash. The topmost coping strategy employed by faculty was buying only basic foods or things for household. The faculty also experienced economic difficulty to a 'moderate extent.' Nevertheless, the performance of the faculty was found to be “outstanding.” Teachers were affected by such financial crisis. However, despite their experienced economic difficulties, as major agents for change, they performed their best for the improvement of quality education. No significant relationships existed between coping strategies and teaching performance of faculty.",'RegionIII','Social Science','http://res.cloudinary.com/dzhe5doam/image/upload/c_fit/sq7yu93wvwntpllnevqd.pdf','HAHAHAHAAHAH',NULL,NULL]);

        DB::insert('insert into journals values(?,?,?,?,?,?,?,?,?,?,?)', [NULL,'Using local ecological knowledge and environmental education in resource management of abalone in Carot, Anda, Pangasinan','Emmanuel C. Capinpin, Jr.','2012-05-01','The objectives of the present study were to (1) determine the local ecological knowledge (LEK) of abalone gatherers through interviews and mentoring, and assess the correspondence between scientific information and LEK, so that areas where local knowledge may be most useful in resource management could be identified, and (2) to empower selected gatherers/farmers with knowledge and technical skills through environmental education to help develop or build their capacity to become sustainable resource managers. The LEK of abalone fishers was determined using three complementary approaches – group interview, individual interview, and mentoring sessions. Local fishers possess a wealth of knowledge about the interactions of species gained through many years of observations, and this knowledge may be useful in guiding biologists in ecological restoration or management regimes. Additionally, the fishers’ LEK, validated by modern scientific ecological findings, could be a source of important and effective ideas in resource management. The knowledge of the abalone gatherers about important abalone fishing grounds should help in pinpointing critical areas that need to be managed. Abalone mariculture in cages should be set up in these areas to routinely create dense breeding populations which can help in enhancing recovery and in providing fishers with a source of additional income. The continued enforcement of marine protected areas and the periodic release or reseeding of abalone in sanctuaries could also be considered viable resource management options. Other recommendations for resource management based on gathered local knowledge and lessons learned from the environmental education (EE) seminars are also presented.','RegionIII','Ecology','http://res.cloudinary.com/dzhe5doam/image/upload/c_fit/izif5qenaadd15kua7nw.pdf','HAHAHAHAAHAH',NULL,NULL]);

        DB::insert('insert into journals values(?,?,?,?,?,?,?,?,?,?,?)', [NULL,'Participatory Metalegal and Legal Processes for the Coastal Development Plan of Bolinao, Pangasinan','Wenceslao N. Asido Jr., Liana Talaue-McManus','2000-12-01','The Coastal Development Plan that was passed into law as the Municipal Fisheries Ordinance of Bolinao, Pangasinan, is a concrete example of community participation in policy development. Among the effective metalegal strategies used during the evolution of the plan into an ordinance were the lobbies staged by the federation of people’s organizations (KAISAKA), the Municipal Fisheries and Aquatic Resources Management Council (MFARMC), and the Municipal Mayor. The capacity of various sectors to participate actively in the passage of the plan was enhanced through legal consultations and training provided by the Marine Fisheries Resources Management Project, in partnership with Tanggol Kalikasan, the legal arm of Haribon Foundation. The experience underscores the need for development projects to include the metalegal training of community constituents as a requisite for the latter to actively participate in the formulation of policies and laws for coastal resources management.','RegionIII','Metallurgy','http://res.cloudinary.com/dzhe5doam/image/upload/c_fit/kllquxwxugolm7rrrp4g.pdf','HAHAHAHAAHAH',NULL,NULL]);


        DB::insert('insert into users values(?,?,?,?,?,?,?,?,?,?)', [NULL,'Vanessa','Romero','vlromero@up.edu.ph','$2y$10$SLfUbQUlopMDrcSXcoNdkuF5ffLAGI3WcUHZ5fXGvSi04JrhCrWQ.',0,'NationalCapitalRegion',NULL,NULL,NULL]);
        DB::insert('insert into users values(?,?,?,?,?,?,?,?,?,?)', [NULL,'Mac','Labasano','mplabasano@up.edu.ph','$2y$10$SLfUbQUlopMDrcSXcoNdkuF5ffLAGI3WcUHZ5fXGvSi04JrhCrWQ.',1,'RegionI',NULL,NULL,NULL]);
        DB::insert('insert into users values(?,?,?,?,?,?,?,?,?,?)', [NULL,'Sample','Two','two@gmail.com','$2y$10$SLfUbQUlopMDrcSXcoNdkuF5ffLAGI3WcUHZ5fXGvSi04JrhCrWQ.',1,'RegionII',NULL,NULL,NULL]);
        DB::insert('insert into users values(?,?,?,?,?,?,?,?,?,?)', [NULL,'Sample','Three','three@gmail.com','$2y$10$SLfUbQUlopMDrcSXcoNdkuF5ffLAGI3WcUHZ5fXGvSi04JrhCrWQ.',1,'RegionIII',NULL,NULL,NULL]);

        DB::insert('insert into subjects values(?,?,?,?)', [NULL,'Agriculture',NULL,NULL]);
        DB::insert('insert into subjects values(?,?,?,?)', [NULL,'Aquaculture',NULL,NULL]);
        DB::insert('insert into subjects values(?,?,?,?)', [NULL,'Business',NULL,NULL]);
        DB::insert('insert into subjects values(?,?,?,?)', [NULL,'Ecology',NULL,NULL]);
        DB::insert('insert into subjects values(?,?,?,?)', [NULL,'Epistemology',NULL,NULL]);
        DB::insert('insert into subjects values(?,?,?,?)', [NULL,'Ethics',NULL,NULL]);
        DB::insert('insert into subjects values(?,?,?,?)', [NULL,'Forensic Science',NULL,NULL]);
        DB::insert('insert into subjects values(?,?,?,?)', [NULL,'History',NULL,NULL]);
        DB::insert('insert into subjects values(?,?,?,?)', [NULL,'Horticulture',NULL,NULL]);
        DB::insert('insert into subjects values(?,?,?,?)', [NULL,'Humanities',NULL,NULL]);
        DB::insert('insert into subjects values(?,?,?,?)', [NULL,'Hydrology',NULL,NULL]);
        DB::insert('insert into subjects values(?,?,?,?)', [NULL,'Metallurgy',NULL,NULL]);
        DB::insert('insert into subjects values(?,?,?,?)', [NULL,'Social Science',NULL,NULL]);
        DB::insert('insert into subjects values(?,?,?,?)', [NULL,'Sociology',NULL,NULL]);


        DB::insert('insert into journal_subject values(?,?,?)', [NULL,1,2]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,2,8]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,2,14]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,3,2]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,4,5]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,4,6]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,5,10]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,6,13]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,7,7]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,8,4]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,9,13]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,10,13]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,11,1]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,12,13]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,13,4]);
        DB::insert('insert into journal_subject values(?,?,?)', [NULL,14,12]);
    }
}
